default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: piazza_development

test:
  <<: *default
  database: piazza_test

production:
  <<: *default
  # database: piazza_production
  # username: piazza
  # password: <%= ENV["PIAZZA_DATABASE_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL'] %>
